#Final project for the data engineering bootcamp of Codigo Facilito

name: run get_data.py

on: 
    workflow_dispatch:
    schedule:
        - cron: "0 15 * * 0"

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: checkout repo content
          uses: actions/checkout@v2

        - name: setup python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'

        - name: install python packages
          run: |
            python3 -m pip install --upgrade pip
            pip install requests
            pip install lxml
            pip install beautifulsoup4
            pip install numpy
            pip install pandas
            pip install snowflake-connector-python
            pip install sqlalchemy
            pip install "snowflake-connector-python[pandas]"

        - name: execute py script
          run: python3 -u -W get_data.py
            
